#!/usr/bin/env python3
import os
import subprocess

class RepoManager:
    """
    The Librarian: Handles the Gentoo environment configuration.
    Manages profiles, keywords, licenses, and repository syncing.
    """
    def __init__(self, base_path="/etc/portage"):
        self.base_path = base_path
        self.repos_conf_path = os.path.join(base_path, "repos.conf")
        self.make_conf_path = os.path.join(base_path, "make.conf")
        
        # Ensure directory structure exists
        os.makedirs(self.repos_conf_path, exist_ok=True)
        if not os.path.exists(self.make_conf_path):
            with open(self.make_conf_path, "w") as f:
                f.write('# Generated by MutMerge Librarian\n')

    def check_profile_validity(self, arch):
        """Checks if the target architecture exists in the Gentoo tree."""
        desc_path = "/var/db/repos/gentoo/profiles/profiles.desc"
        if not os.path.exists(desc_path):
            print("⚠️ Librarian: profiles.desc missing! Is the tree synced at /var/db/repos/gentoo?")
            return False
            
        with open(desc_path, "r") as f:
            content = f.read()
            if f"default/linux/{arch}" in content:
                print(f"✅ Librarian: {arch} is a valid mutation target.")
                return True
        
        print(f"❌ Librarian: {arch} not found in profiles.desc!")
        return False

    def finalize_profile_stack(self, arch, use_systemd=False):
        """
        Creates the /etc/portage/make.profile/parent stack.
        Hierarchy: Base -> Hardened -> Desktop -> Pentoo
        """
        profile_path = os.path.join(self.base_path, "make.profile")
        
        # In a container, we replace the symlink with a directory + parent file
        if os.path.islink(profile_path):
            os.unlink(profile_path)
        os.makedirs(profile_path, exist_ok=True)

        stack = [
            f"gentoo:default/linux/{arch}/23.0",
            "gentoo:targets/hardened",
            "gentoo:targets/desktop",
        ]
        
        if use_systemd:
            stack.append("gentoo:targets/desktop/systemd")
        
        stack.append("pentoo:pentoo/overlay")

        with open(os.path.join(profile_path, "parent"), "w") as f:
            for atom in stack:
                f.write(f"{atom}\n")
        
        print(f"🧬 Librarian: Profile stacked for {arch} (Hardened + Desktop + Pentoo).")

    def generate_global_masks(self):
        """Silences build-heavy, non-functional flags globally."""
        mask_dir = os.path.join(self.base_path, "package.use")
        os.makedirs(mask_dir, exist_ok=True)
        
        content = "# Global Mutation Masks to speed up the Ladder\n"
        content += "*/* -doc -test -handbook -examples\n"
        
        with open(os.path.join(mask_dir, "mutmerge"), "w") as f:
            f.write(content)
        print("🧬 Librarian: Global Mutation Masks (-doc -test) applied.")

    def accept_all_buffet_keywords(self, config_manager, arch):
        """Unmasks all packages in the Buffet for the target architecture."""
        keywords_path = os.path.join(self.base_path, "package.accept_keywords")
        os.makedirs(keywords_path, exist_ok=True)
        
        packages = config_manager.get_packages()
        
        with open(os.path.join(keywords_path, "mutmerge"), "w") as f:
            f.write(f"# Auto-generated by MutMerge for {arch}\n")
            for pkg_cp in packages.keys():
                # Allow stable, testing (~arch), and live (**)
                f.write(f"{pkg_cp} {arch} ~{arch} **\n")
        
        print(f"🧬 Librarian: Keywords accepted for {len(packages)} packages (~{arch} **).")

    def grant_all_licenses(self):
        """Ensures unattended builds never stop for EULAs."""
        with open(self.make_conf_path, "a+") as f:
            f.seek(0)
            if 'ACCEPT_LICENSE="*"' not in f.read():
                f.write('\n# Auto-granted for unattended mutation\n')
                f.write('ACCEPT_LICENSE="*" \n')
        print("🧬 Librarian: All Licenses (*) accepted.")

    def setup_binary_instance(self, arch):
        """Enables multi-instance support for the binhost showroom."""
        with open(self.make_conf_path, "a+") as f:
            f.seek(0)
            content = f.read()
            if 'binpkg-multi-instance' not in content:
                f.write('\nFEATURES="${FEATURES} binpkg-multi-instance"\n')
                f.write(f'PKGDIR="/srv/binhosts/{arch}"\n')
        print(f"🧬 Librarian: Multi-instance binary support enabled for {arch}.")

    def sync_repos_from_toml(self, config_manager):
        """Generates repos.conf from the repositories defined in the Buffet."""
        repos = config_manager.get_repositories()
        for name, url in repos.items():
            repo_file = os.path.join(self.repos_conf_path, f"{name}.conf")
            content = f"[{name}]\nlocation = /var/db/repos/{name}\nsync-type = git\nsync-uri = {url}\n"
            with open(repo_file, "w") as f:
                f.write(content)
        print(f"📖 Librarian: {len(repos)} repositories indexed in repos.conf.")

    def final_infrastructure_sync(self, config_manager, arch):
        """The Master Sync: Executes the full environmental preparation."""
        self.finalize_profile_stack(arch)
        self.generate_global_masks()
        self.accept_all_buffet_keywords(config_manager, arch)
        self.grant_all_licenses()
        self.setup_binary_instance(arch)
        self.sync_repos_from_toml(config_manager)
        print(f"🏁 Librarian: Infrastructure synchronized for {arch}.")
